// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njhcuwtsiijkqqtsywkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qaGN1d3RzaWlqa3FxdHN5d2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTExMjksImV4cCI6MjA2Njk2NzEyOX0.orgk-B4AeEBT99xD495xUQdrQdBDLr1Mdlwy--ADjoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});